name: erp
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: ""
      DB_PORT: ""
      REDIS_CACHE: ""
      REDIS_QUEUE: ""
      SOCKETIO_PORT: "9000"
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    image: zapal/erp:v15.12.2
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
      - type: volume
        source: erp-bench
        target: /home/frappe/frappe-bench
        volume: {}
networks:
  default:
    name: erp_default
volumes:
  erp-bench:
    name: erp_erp-bench
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: zapal/erp:v15.12.2
  pull_policy: always
  volumes:
    - erp-bench:/home/frappe/frappe-bench
x-customizable-image:
  image: zapal/erp:v15.12.2
  pull_policy: always
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
