version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"

  frappe:
    volumes:
     - ./frappe:/home/frappe
    build: .
    ports:
     - "8000:8000"
    stdin_open: true
    tty: true
    links:
      - redis
      - mariadb
    depends_on:
      - mariadb
      - redis
    
