apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erpnext.fullname" . }}-redis-queue
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-redis-queue
      app.kubernetes.io/instance: {{ .Release.Name }}-redis-queue
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erpnext.name" . }}-redis-queue
        app.kubernetes.io/instance: {{ .Release.Name }}-redis-queue
    spec:
      containers:
      - name: master
        image: redis:5-alpine
        resources:
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
