name: build system Image base on json config provided
# run-name: ${{ github.actor }} update 🚀


on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, reopened]
  #   branches: [main]
  # workflow_call:
    

# on:
  # workflow_run:
#     workflows: ["Master Workflow"]
#     types:
#       - completed

   
jobs:
  job-image-build:
    runs-on:
     - self-hosted
     # - ubuntu-latest
   

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: login to harb
        uses: docker/login-action@v1
        with:
          registry: harbor.fintechsys.net
          username: ${{ secrets.PHEE_HARBOR_USERNAME  }}
          password: ${{ secrets.PHEE_HARBOR_PASSWORD }}
      - name: Execute custom commands
        run: |
          git clone  https://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@github.com/malnozili/remittance_image_builder.git
          cd remittance_image_builder
          
          ../build_network_company_image.sh --tag="remittance_network_agent/${{ vars.BRANCH_NAME }}:latest" --token="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" --frappe-path="https://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@github.com/fintechsys/frappe.git" --frappe-branch=latest
          
        # docker image ls
        # docker tag remittance_network_agent/${{ vars.BRANCH_NAME }}:latest harbor.fintechsys.net/frappe-systems/${{ vars.BRANCH_NAME }}:latest
        # docker push harbor.fintechsys.net/frappe-systems/remittance_network_agent/${{ vars.BRANCH_NAME }}:latest
       
      #Creat Bench and sites
      
      - name: Create first bench
        run: |
          echo 'The branch name is' $BRANCH_NAME
          cp example.env ~/gitopss/erpnext-one.env
          sed -i 's/DB_PASSWORD=123/DB_PASSWORD=${{ vars.MARIADB_PASSWORD }}/g' ~/gitopss/erpnext-one.env
          sed -i 's/DB_HOST=/DB_HOST=mariadb-database/g' ~/gitopss/erpnext-one.env
          sed -i 's/DB_PORT=/DB_PORT=3306/g' ~/gitopss/erpnext-one.env
          sed -i 's/SITES=`erp.fintechsys.net`/SITES=\`${{ vars.SITE_NAME }}\`/g' ~/gitopss/erpnext-one.env
          echo 'ROUTER=erpnext-one' >> ~/gitopss/erpnext-one.env
          echo "BENCH_NETWORK=${{ vars.BRANCH_NAME }}" >> ~/gitopss/erpnext-one.env

      - name: Create a yaml file to deploy container
        run: |
          docker compose --project-name ${{ vars.BRANCH_NAME }} \
          --env-file ~/gitopss/erpnext-one.env \
          -f compose.yaml \
          -f overrides/compose.redis.yaml \
          -f overrides/compose.multi-bench.yaml \
          -f overrides/compose.multi-bench-ssl.yaml config > ~/gitopss/erpnext-one.yaml


      - name: Deploy the container
        run: |
          docker compose --project-name ${{ vars.BRANCH_NAME }} -f ~/gitopss/erpnext-one.yaml up -d 

      
      - name: Create the site
        run: | 
          docker compose --project-name ${{ vars.BRANCH_NAME }} exec -T backend \
            bench new-site --no-mariadb-socket --mariadb-root-password ${{ vars.MARIADB_PASSWORD }} --install-app hrms --set-default \
                 --install-app rule_management --install-app remittance_base --install-app remittance --install-app bulk_remittance --install-app remittance_stellar_integration \
                 --install-app client_account_management  --install-app teller_for_erpnext --install-app teller_for_agent \
                 --install-app remittance_agent_service --install-app payment_management --install-app bank_services --install-app remittance_customize \
                 --install-app remittance_network_manager --install-app erpnext_theme --install-app remittance_website --admin-password ${{ vars.MARIADB_PASSWORD }}  ${{ vars.SITE_NAME }}
      
