name: build system Image base on json config provided
run-name: ${{ github.actor }} update 🚀
on: [push, pull_request]

jobs:
  job-image-build:
    runs-on: ubuntu-latest
    # env: working-directory:./

    steps:
      - name: checkout Script content
        uses: actions/checkout@v2 
     
    
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Change to the desired Java version
          distribution: 'adopt'
      
        
      - name: Execute custom commands
        run: |
          echo "Build Jar"./mvnw install# working-directory:./
        uses: docker/login-action@v1
        with:
          registry: harbor.fintechsys.net
          username: ${{ secrets.PHEE_HARBOR_USERNAME  }}
          password: ${{ secrets.PHEE_HARBOR_PASSWORD }}
      
      - name: BuildAndPushImageOnHarbor
        uses: actions/checkout@v3
        run: |
            docker build ./ -t harbor.fintechsys.net/yemen-express/sync-remit-dispatcher:latest
            docker push harbor.fintechsys.net/yemen-express/sync-remit-dispatcher:latest
