name: build system Image base on json config provided
run-name: ${{ github.actor }} update 🚀


on:
  workflow_dispatch:

# on:
#   workflow_run:
#     workflows: ["Master Workflow"]
#     types:
#       - completed

   
jobs:
  job-image-build:
    runs-on:
     - self-hosted
   

    steps:
      - name: login to harb
        uses: docker/login-action@v1
        with:
          registry: harbor.fintechsys.net
          username: ${{ secrets.PHEE_HARBOR_USERNAME  }}
          password: ${{ secrets.PHEE_HARBOR_PASSWORD }}
      - name: Execute custom commands
        run: |
          git clone --recursive "https://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@github.com/fintechsys/remittance_image_builder.git"
          cd remittance_image_builder
          
          ../build_network_company_image.sh --tag="remittance_network_agent:version-14" --token="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" --frappe-path="https://github.com/fintechsys/frappe.git" --frappe-branch=version-14
          
          docker image ls
          docker tag remittance_network_agent:version-14 harbor.fintechsys.net/frappe-systems/devlop:version-14
          docker push harbor.fintechsys.net/frappe-systems/remittance_network_agent:version-14
       
      
