name: build system Image base on json config provided
run-name: ${{ github.actor }} update 🚀


on:
  workflow_dispatch:

# on:
#   workflow_run:
#     workflows: ["Master Workflow"]
#     types:
#       - completed

   
jobs:
  job-image-build:
    runs-on:
     - self-hosted
   

    steps:
      - name: login to harb
        uses: docker/login-action@v1
        with:
          registry: harbor.fintechsys.net
          username: ${{ secrets.PHEE_HARBOR_USERNAME  }}
          password: ${{ secrets.PHEE_HARBOR_PASSWORD }}
      - name: Execute custom commands
        run: |
          git clone --recursive "https://${{ secrets.REMITTANCE_NETWORK_AGENT  }}@github.com/fintechsys/remittance_image_builder.git"
          cd remittance_image_builder
          
          ./build_network_company_image.sh --tag="develop-${{ secrets.BRANCH_NAME_JS  }}:latest" --token=${{ secrets.REMITTANCE_NETWORK_AGENT  }} --frappe-path="https://github.com/fintechsys/frappe.git" --frappe-branch=${{ secrets.BRANCH_NAME_JS  }}
          
          docker image ls
          docker tag develop-${{ secrets.BRANCH_NAME_JS  }}:latest harbor.fintechsys.net/frappe-systems/develop-${{ secrets.BRANCH_NAME_JS  }}:latest
          docker push harbor.fintechsys.net/frappe-systems/develop-${{ secrets.BRANCH_NAME_JS  }}:latest
       
      
