name: create site

on:
  workflow_dispatch:

jobs:
  rcreate_site:
    runs-on: self-hosted
     

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this if you have any Python dependencies

    - name: Run create site Script
      run: python fintechsys/create_site.py

