name: test

on:
  workflow_dispatch:

jobs:
#   job-image-build: 
#     runs-on:
#      - self-hosted
  call_workflow_using_branch:
     uses: .github/workflows/Reusable_build_image.yml@master


     

    
