name: Master Workflow

on:
  workflow_dispatch:

jobs:
  run-workflows:
    runs-on: 
       - self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Deploy Traefik and MariaDB
        uses: ./.github/workflows/Deploy_Traefik_and_MariaDB.yml

      - name: Run build system Image base on json config provided
        uses: ./.github/workflows/build_system_image.yml

      - name: Run setup site base on provided image build for branch specified
        uses: ./.github/workflows/setup_site.yml
