name: starter workflow

on:
  workflow_dispatch:

jobs:
  call_workflow_using_branch:
    uses: fal7w/fork-foxs/remittance_image_builder/.github/workflows/Reusable_build_image.yml@master


     

    
